version: "3.7"

x-defaults: &defaults
    init: true
    volumes:
        - ./entrypoints:/entrypoints
    entrypoint: /bin/sh
    deploy:
        replicas: 1
        restart_policy:
            condition: on-failure
            delay: 5s

services:
    pd:
        <<: *defaults
        image: pingcap/pd
        hostname: "pd.tikv"
        init: true
        ports:
            - "2379:2379"
            - "2380:2380"
        command: /entrypoints/pd.sh
    tikv:
        <<: *defaults
        image: pingcap/tikv
        hostname: "tikv.tikv"
        ports:
            - "20160:20160"
        command: /entrypoints/tikv.sh
